import type { Migration } from '../migrate'

/**
 * Drafts (roadmap 2.8): server-side draft storage, so a draft survives a
 * reload and a device change. A separate table instead of outbox_message
 * with a 'draft' status: drafts are edited many times, may be incomplete
 * (no recipient yet) and never trigger a send job.
 *
 * - `id`: generated by the client (UUID), so autosave is an idempotent
 *   PUT /api/drafts/:id - also when replayed from the offline queue.
 * - `content_enc`: to/cc/bcc as typed (raw field text), subject and plain
 *   text as JSON, encrypted with the account DEK (AAD `draft.content:<id>`).
 *   Cleared when the draft is deleted or sent.
 * - `version`: incremented on every save; a save with an outdated
 *   `baseVersion` is answered 409 (conflict between devices).
 * - IMAP copy in the account's Drafts folder (draft_sync job):
 *   `imap_version` is the version uploaded last, `message_id_header` the
 *   Message-ID of that copy (`<draft id>.<version>@domain`, new per version
 *   so the message sync never keeps stale metadata).
 * - `source_*`: location of a draft written in another client that was
 *   opened for editing here; that copy is removed on the first upload, on
 *   delete and after sending.
 * - `deleted_at`: soft delete (discarded or sent); the draft_sync job
 *   removes the IMAP copy and then deletes the row.
 */
export const migration0016 = {
  name: '0016_drafts',
  sql: /* sql */ `
    CREATE TABLE draft (
      id                  uuid PRIMARY KEY,
      account_id          uuid NOT NULL REFERENCES mail_account (id) ON DELETE CASCADE,
      identity_id         uuid REFERENCES identity (id) ON DELETE SET NULL,
      content_enc         bytea,
      in_reply_to         text,
      "references"        text[] NOT NULL DEFAULT '{}',
      version             integer NOT NULL DEFAULT 1,
      imap_version        integer NOT NULL DEFAULT 0,
      message_id_header   text,
      source_folder_id    uuid REFERENCES folder (id) ON DELETE SET NULL,
      source_uidvalidity  bigint,
      source_uid          bigint,
      created_at          timestamptz NOT NULL DEFAULT now(),
      updated_at          timestamptz NOT NULL DEFAULT now(),
      deleted_at          timestamptz
    );
    CREATE INDEX draft_account_idx ON draft (account_id, updated_at DESC)
      WHERE deleted_at IS NULL;
    CREATE INDEX draft_message_id_idx ON draft (account_id, message_id_header)
      WHERE deleted_at IS NULL;
  `,
} satisfies Migration
