/**
 * Drafts API (roadmap 2.8): server-side drafts, so a draft survives a
 * reload and a device change.
 *
 * - `PUT /api/drafts/:id` creates or replaces a draft (autosave). The id is
 *   generated by the client, so a save replayed from the offline queue is
 *   idempotent. Only a save without `baseVersion` (or 0) creates a draft; a
 *   later save of a sent or discarded draft answers 410. Content is stored encrypted with the account DEK
 *   (`draft.content_enc`). Lost updates across devices: the client sends
 *   the version it edited (`baseVersion`); if the draft was saved elsewhere
 *   meanwhile the answer is 409 with the current draft, unless `force`
 *   (last write wins, chosen by the user or used by offline replays).
 * - `GET /api/drafts/:id`, `GET /api/accounts/:id/drafts` read drafts.
 * - `DELETE /api/drafts/:id` discards a draft (idempotent). Sending a
 *   draft = `POST /api/outbox` with `draftId` (see ./outbox).
 * - `POST /api/messages/:id/draft` opens a message of the IMAP Drafts
 *   folder (e.g. written in another client) for editing: returns the draft
 *   it belongs to, or creates one from it that replaces the IMAP copy on
 *   the first upload.
 *
 * Every save, delete and send enqueues a coalesced `draft_sync` job: the
 * worker mirrors the draft into the account's Drafts folder (or removes
 * it). Autosaves are delayed by DRAFT_UPLOAD_DELAY_MS so a burst of saves
 * ends in one IMAP upload.
 *
 * Ownership: everything is scoped via mail_account.user_id; foreign or
 * unknown ids answer 404. Decrypted content is never logged.
 */
import { randomUUID } from 'node:crypto'
import type { FastifyBaseLogger, FastifyInstance } from 'fastify'
import {
  decryptField,
  draftContentAad,
  encryptField,
  messageFieldAad,
  unwrapAccountKey,
} from '@fma/crypto'
import { enqueueDraftSync } from '@fma/db/job-queue'
import {
  DRAFT_LIMITS,
  formatAddressList,
  isValidMessageId,
  type Draft,
  type DraftConflictResponse,
  type DraftContent,
  type DraftListResponse,
  type MailPerson,
} from '@fma/shared'
import { requireAuth } from '../auth/routes'

const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i
/** Message-ID of an uploaded draft version: `<draft id>.<version>@domain`. */
const DRAFT_MESSAGE_ID_RE =
  /^<([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})\.\d+@/i
/** Delay of the IMAP upload after an autosave (coalesces bursts of saves). */
export const DRAFT_UPLOAD_DELAY_MS = 15_000
/** Generous body limit for long plain-text drafts (UTF-8 up to 4 bytes/char). */
const BODY_LIMIT_BYTES = 4 * 1024 * 1024
const LIST_LIMIT = 200
const GONE_MESSAGE = 'Der Entwurf wurde inzwischen gesendet oder verworfen.'

interface DraftRow {
  id: string
  account_id: string
  identity_id: string | null
  content_enc: Buffer | null
  in_reply_to: string | null
  references: string[]
  version: number
  created_at: Date
  updated_at: Date
  deleted_at: Date | null
  wrapped_dek: Buffer
  message_ids: string[]
}

const DRAFT_SELECT = /* sql */ `
  SELECT d.id, d.account_id, d.identity_id, d.content_enc, d.in_reply_to, d."references",
         d.version, d.created_at, d.updated_at, d.deleted_at, a.wrapped_dek,
         coalesce((SELECT array_agg(m.id::text) FROM message m
                   WHERE d.message_id_header IS NOT NULL AND m.account_id = d.account_id
                     AND m.message_id_header = d.message_id_header), '{}') AS message_ids
  FROM draft d JOIN mail_account a ON a.id = d.account_id`

interface ParsedDraftRequest extends DraftContent {
  accountId: string
  identityId: string | null
  inReplyTo: string | null
  references: string[]
  baseVersion?: number
  force: boolean
}

function masterKey(): string {
  return process.env.MASTER_KEY ?? ''
}

/** Validates a save request; returns a German error message on failure. */
export function parseDraftRequest(body: unknown): ParsedDraftRequest | string {
  if (!body || typeof body !== 'object') return 'Ungültige Anfrage.'
  const input = body as Record<string, unknown>
  if (typeof input.accountId !== 'string' || !UUID_RE.test(input.accountId)) {
    return 'Ungültiges Konto.'
  }
  const identityId = input.identityId ?? null
  if (identityId !== null && (typeof identityId !== 'string' || !UUID_RE.test(identityId))) {
    return 'Ungültige Absenderidentität.'
  }
  for (const field of ['to', 'cc', 'bcc'] as const) {
    const value = input[field] ?? ''
    if (typeof value !== 'string') return 'Ungültige Empfängerangabe.'
    if (value.length > DRAFT_LIMITS.maxAddressFieldLength) return 'Zu viele Empfänger.'
  }
  if (typeof input.subject !== 'string') return 'Ungültiger Betreff.'
  if (input.subject.length > DRAFT_LIMITS.maxSubjectLength) return 'Der Betreff ist zu lang.'
  if (typeof input.text !== 'string') return 'Ungültiger Nachrichtentext.'
  if (input.text.length > DRAFT_LIMITS.maxTextLength) return 'Der Nachrichtentext ist zu lang.'
  const inReplyTo = input.inReplyTo ?? null
  if (inReplyTo !== null && !isValidMessageId(inReplyTo)) return 'Ungültiger In-Reply-To-Header.'
  const references = input.references ?? []
  if (
    !Array.isArray(references) ||
    references.length > DRAFT_LIMITS.maxReferences ||
    !references.every(isValidMessageId)
  ) {
    return 'Ungültiger References-Header.'
  }
  const baseVersion = input.baseVersion
  if (
    baseVersion !== undefined &&
    (!Number.isInteger(baseVersion) || (baseVersion as number) < 0)
  ) {
    return 'Ungültige Version.'
  }
  if (input.force !== undefined && typeof input.force !== 'boolean') return 'Ungültige Anfrage.'
  return {
    accountId: input.accountId.toLowerCase(),
    identityId: identityId?.toLowerCase() ?? null,
    to: (input.to as string | undefined) ?? '',
    cc: (input.cc as string | undefined) ?? '',
    bcc: (input.bcc as string | undefined) ?? '',
    // No line breaks in the subject (it becomes a header of the IMAP copy).
    subject: input.subject.replace(/[\r\n]+/g, ' '),
    text: input.text,
    inReplyTo,
    references: references as string[],
    baseVersion: baseVersion as number | undefined,
    force: input.force === true,
  }
}

function encryptContent(dek: Buffer, id: string, content: DraftContent): Buffer {
  return Buffer.from(encryptField(dek, JSON.stringify(content), draftContentAad(id)), 'utf8')
}

function toDraft(log: FastifyBaseLogger, row: DraftRow): Draft {
  let content: DraftContent = { to: '', cc: '', bcc: '', subject: '', text: '' }
  if (row.content_enc) {
    try {
      const dek = unwrapAccountKey(masterKey(), row.wrapped_dek)
      content = {
        ...content,
        ...(JSON.parse(
          decryptField(dek, row.content_enc.toString('utf8'), draftContentAad(row.id)),
        ) as Partial<DraftContent>),
      }
    } catch {
      log.warn({ draftId: row.id }, 'draft content could not be decrypted')
    }
  }
  return {
    id: row.id,
    accountId: row.account_id,
    identityId: row.identity_id,
    to: content.to,
    cc: content.cc,
    bcc: content.bcc,
    subject: content.subject,
    text: content.text,
    inReplyTo: row.in_reply_to,
    references: row.references,
    version: row.version,
    createdAt: row.created_at.toISOString(),
    updatedAt: row.updated_at.toISOString(),
    messageIds: row.message_ids,
  }
}

/** Person lists of a synced message are JSON `[{ name, address }]` (see message sync). */
function toPeople(value: unknown): MailPerson[] {
  if (!Array.isArray(value)) return []
  return value
    .filter((entry): entry is MailPerson => typeof entry?.address === 'string')
    .map((entry) => ({ name: String(entry.name ?? ''), address: entry.address }))
}

export async function draftRoutes(app: FastifyInstance): Promise<void> {
  const pool = app.authPool

  async function loadOwned(id: string, userId: string): Promise<DraftRow | null> {
    if (!UUID_RE.test(id)) return null
    const { rows } = await pool.query<DraftRow>(
      `${DRAFT_SELECT} WHERE d.id = $1 AND a.user_id = $2 AND d.deleted_at IS NULL`,
      [id, userId],
    )
    return rows[0] ?? null
  }

  async function ownsAccount(accountId: string, userId: string): Promise<Buffer | null> {
    if (!UUID_RE.test(accountId)) return null
    const { rows } = await pool.query<{ wrapped_dek: Buffer }>(
      'SELECT wrapped_dek FROM mail_account WHERE id = $1 AND user_id = $2',
      [accountId, userId],
    )
    return rows[0]?.wrapped_dek ?? null
  }

  app.put<{ Params: { id: string }; Body: unknown }>(
    '/api/drafts/:id',
    { preHandler: requireAuth, bodyLimit: BODY_LIMIT_BYTES },
    async (request, reply) => {
      const id = request.params.id.toLowerCase()
      if (!UUID_RE.test(id)) {
        await reply.code(404).send({ message: 'Entwurf nicht gefunden.' })
        return
      }
      const parsed = parseDraftRequest(request.body)
      if (typeof parsed === 'string') {
        await reply.code(400).send({ message: parsed })
        return
      }
      const userId = request.auth!.userId
      const wrappedDek = await ownsAccount(parsed.accountId, userId)
      if (!wrappedDek) {
        await reply.code(404).send({ message: 'Konto nicht gefunden.' })
        return
      }
      if (parsed.identityId) {
        const { rowCount } = await pool.query(
          'SELECT 1 FROM identity WHERE id = $1 AND account_id = $2',
          [parsed.identityId, parsed.accountId],
        )
        if (!rowCount) {
          await reply.code(404).send({ message: 'Absenderidentität nicht gefunden.' })
          return
        }
      }

      const dek = unwrapAccountKey(masterKey(), wrappedDek)
      const contentEnc = encryptContent(dek, id, {
        to: parsed.to,
        cc: parsed.cc,
        bcc: parsed.bcc,
        subject: parsed.subject,
        text: parsed.text,
      })

      const client = await pool.connect()
      let created = false
      try {
        await client.query('BEGIN')
        // Insert or lock the existing row (concurrent saves of one draft
        // serialize here). A save based on an existing version never creates
        // the draft again: once sent or discarded, its row may be gone.
        if (!parsed.baseVersion) {
          const inserted = await client.query(
            `INSERT INTO draft (id, account_id, identity_id, content_enc, in_reply_to, "references")
             VALUES ($1, $2, $3, $4, $5, $6)
             ON CONFLICT (id) DO NOTHING`,
            [
              id,
              parsed.accountId,
              parsed.identityId,
              contentEnc,
              parsed.inReplyTo,
              parsed.references,
            ],
          )
          created = (inserted.rowCount ?? 0) > 0
        }
        if (!created) {
          const { rows } = await client.query<{
            account_id: string
            user_id: string
            version: number
            deleted_at: Date | null
          }>(
            `SELECT d.account_id, a.user_id, d.version, d.deleted_at
             FROM draft d JOIN mail_account a ON a.id = d.account_id
             WHERE d.id = $1 FOR UPDATE OF d`,
            [id],
          )
          const existing = rows[0]
          if (!existing) {
            await client.query('ROLLBACK')
            await reply.code(410).send({ message: GONE_MESSAGE })
            return
          }
          if (existing.user_id !== userId || existing.account_id !== parsed.accountId) {
            await client.query('ROLLBACK')
            await reply.code(404).send({ message: 'Entwurf nicht gefunden.' })
            return
          }
          if (existing.deleted_at) {
            await client.query('ROLLBACK')
            await reply.code(410).send({ message: GONE_MESSAGE })
            return
          }
          if (
            parsed.baseVersion !== undefined &&
            parsed.baseVersion !== existing.version &&
            !parsed.force
          ) {
            await client.query('ROLLBACK')
            const current = await loadOwned(id, userId)
            const body: DraftConflictResponse = {
              message: 'Der Entwurf wurde inzwischen auf einem anderen Gerät geändert.',
              draft: toDraft(request.log, current!),
            }
            await reply.code(409).send(body)
            return
          }
          await client.query(
            `UPDATE draft SET identity_id = $2, content_enc = $3, in_reply_to = $4,
               "references" = $5, version = version + 1, updated_at = now()
             WHERE id = $1`,
            [id, parsed.identityId, contentEnc, parsed.inReplyTo, parsed.references],
          )
        }
        await enqueueDraftSync(client, parsed.accountId, id, DRAFT_UPLOAD_DELAY_MS)
        await client.query('COMMIT')
      } catch (err) {
        await client.query('ROLLBACK').catch(() => {})
        throw err
      } finally {
        client.release()
      }
      const row = await loadOwned(id, userId)
      await reply.code(created ? 201 : 200).send(toDraft(request.log, row!))
    },
  )

  app.get<{ Params: { id: string } }>(
    '/api/drafts/:id',
    { preHandler: requireAuth },
    async (request, reply) => {
      const row = await loadOwned(request.params.id, request.auth!.userId)
      if (!row) {
        await reply.code(404).send({ message: 'Entwurf nicht gefunden.' })
        return
      }
      await reply.send(toDraft(request.log, row))
    },
  )

  app.get<{ Params: { id: string } }>(
    '/api/accounts/:id/drafts',
    { preHandler: requireAuth },
    async (request, reply) => {
      const accountId = request.params.id
      if (!(await ownsAccount(accountId, request.auth!.userId))) {
        await reply.code(404).send({ message: 'Konto nicht gefunden.' })
        return
      }
      const { rows } = await pool.query<DraftRow>(
        `${DRAFT_SELECT}
         WHERE d.account_id = $1 AND d.deleted_at IS NULL
         ORDER BY d.updated_at DESC, d.id
         LIMIT ${LIST_LIMIT}`,
        [accountId],
      )
      const body: DraftListResponse = { drafts: rows.map((row) => toDraft(request.log, row)) }
      await reply.send(body)
    },
  )

  app.delete<{ Params: { id: string } }>(
    '/api/drafts/:id',
    { preHandler: requireAuth },
    async (request, reply) => {
      const id = request.params.id
      if (!UUID_RE.test(id)) {
        await reply.code(404).send({ message: 'Entwurf nicht gefunden.' })
        return
      }
      const { rows } = await pool.query<{ account_id: string; user_id: string }>(
        `SELECT d.account_id, a.user_id FROM draft d JOIN mail_account a ON a.id = d.account_id
         WHERE d.id = $1`,
        [id],
      )
      const row = rows[0]
      if (row && row.user_id !== request.auth!.userId) {
        await reply.code(404).send({ message: 'Entwurf nicht gefunden.' })
        return
      }
      // Unknown or already deleted: nothing to do (idempotent, offline replays).
      if (row) {
        const client = await pool.connect()
        try {
          await client.query('BEGIN')
          const { rowCount } = await client.query(
            `UPDATE draft SET deleted_at = now(), content_enc = NULL, updated_at = now()
             WHERE id = $1 AND deleted_at IS NULL`,
            [id],
          )
          if (rowCount) await enqueueDraftSync(client, row.account_id, id)
          await client.query('COMMIT')
        } catch (err) {
          await client.query('ROLLBACK').catch(() => {})
          throw err
        } finally {
          client.release()
        }
      }
      await reply.code(204).send()
    },
  )

  app.post<{ Params: { id: string } }>(
    '/api/messages/:id/draft',
    { preHandler: requireAuth },
    async (request, reply) => {
      const messageId = request.params.id
      const userId = request.auth!.userId
      if (!UUID_RE.test(messageId)) {
        await reply.code(404).send({ message: 'Nachricht nicht gefunden.' })
        return
      }
      const client = await pool.connect()
      let draftId: string
      let created = false
      try {
        await client.query('BEGIN')
        // Locks the message: a double click resumes the same draft.
        const { rows } = await client.query<{
          account_id: string
          wrapped_dek: Buffer
          message_id_header: string
          in_reply_to: string | null
          references: string[]
          subject_enc: Buffer
          recipients_enc: Buffer
          text_plain_enc: Buffer | null
        }>(
          `SELECT m.account_id, a.wrapped_dek, m.message_id_header, m.in_reply_to, m."references",
                  m.subject_enc, m.recipients_enc, mb.text_plain_enc
           FROM message m
           JOIN mail_account a ON a.id = m.account_id
           LEFT JOIN message_body mb ON mb.message_id = m.id
           WHERE m.id = $1 AND a.user_id = $2
           FOR UPDATE OF m`,
          [messageId, userId],
        )
        const message = rows[0]
        if (!message) {
          await client.query('ROLLBACK')
          await reply.code(404).send({ message: 'Nachricht nicht gefunden.' })
          return
        }

        // A copy uploaded by this app, or a draft already opened from this message.
        const ownId = DRAFT_MESSAGE_ID_RE.exec(message.message_id_header)?.[1]?.toLowerCase()
        const { rows: existing } = await client.query<{ id: string }>(
          `SELECT id FROM draft
           WHERE account_id = $1 AND deleted_at IS NULL
             AND (id = $2::uuid OR message_id_header = $3)
           ORDER BY (id = $2::uuid) DESC LIMIT 1`,
          [
            message.account_id,
            ownId ?? '00000000-0000-0000-0000-000000000000',
            message.message_id_header,
          ],
        )
        if (existing[0]) {
          draftId = existing[0].id
        } else {
          if (!message.text_plain_enc) {
            await client.query('ROLLBACK')
            await reply
              .code(409)
              .send({ message: 'Der Inhalt dieses Entwurfs ist noch nicht synchronisiert.' })
            return
          }
          const dek = unwrapAccountKey(masterKey(), message.wrapped_dek)
          const decrypt = (value: Buffer, field: 'subject' | 'recipients' | 'text') =>
            decryptField(dek, value.toString('utf8'), messageFieldAad(field, messageId))
          const recipients = JSON.parse(decrypt(message.recipients_enc, 'recipients')) as {
            to?: unknown
            cc?: unknown
          }
          draftId = randomUUID()
          created = true
          const { rows: locations } = await client.query<{
            folder_id: string
            uidvalidity: string
            uid: string
          }>(
            `SELECT ml.folder_id, ml.uidvalidity, ml.uid
             FROM message_location ml JOIN folder f ON f.id = ml.folder_id
             WHERE ml.message_id = $1 AND ml.uid > 0
             ORDER BY (f.special_use = 'drafts') DESC NULLS LAST LIMIT 1`,
            [messageId],
          )
          const location = locations[0]
          // Not uploaded until edited (imap_version = version): the original
          // copy stays in the Drafts folder until then.
          await client.query(
            `INSERT INTO draft
               (id, account_id, content_enc, in_reply_to, "references", version, imap_version,
                message_id_header, source_folder_id, source_uidvalidity, source_uid)
             VALUES ($1, $2, $3, $4, $5, 1, 1, $6, $7, $8, $9)`,
            [
              draftId,
              message.account_id,
              encryptContent(dek, draftId, {
                to: formatAddressList(toPeople(recipients.to)),
                cc: formatAddressList(toPeople(recipients.cc)),
                bcc: '',
                subject: decrypt(message.subject_enc, 'subject'),
                text: decrypt(message.text_plain_enc, 'text'),
              }),
              message.in_reply_to,
              message.references,
              message.message_id_header,
              location?.folder_id ?? null,
              location?.uidvalidity ?? null,
              location?.uid ?? null,
            ],
          )
        }
        await client.query('COMMIT')
      } catch (err) {
        await client.query('ROLLBACK').catch(() => {})
        throw err
      } finally {
        client.release()
      }
      const row = await loadOwned(draftId, userId)
      await reply.code(created ? 201 : 200).send(toDraft(request.log, row!))
    },
  )
}
