/**
 * Sending API (roadmap 2.7): hands plain-text messages to the SMTP worker
 * and reports their status.
 *
 * - `POST /api/outbox` validates the message, stores it encrypted with the
 *   account DEK (`outbox_message.content_enc`) and enqueues a
 *   `send_message` job in the same transaction. The Message-ID is
 *   generated here, once, so retries and the copy in "Sent" share it.
 * - `GET /api/outbox/:id`, `GET /api/accounts/:id/outbox` report status and
 *   error code (with a German message from @fma/shared).
 * - `POST /api/outbox/:id/retry` re-queues a failed message.
 * - Idempotency (roadmap 4.6): an optional `clientId` (UUID, generated by
 *   the client once per message) makes POST /api/outbox repeatable - the
 *   offline queue replays it, and a repeat with a known id answers 200 with
 *   the existing entry instead of sending again.
 * - Drafts (roadmap 2.8): `draftId` names the draft the message was written
 *   in; it is deleted in the same transaction (the worker then removes its
 *   copy from the IMAP Drafts folder).
 *
 * Ownership: everything is scoped via mail_account.user_id; foreign or
 * unknown ids answer 404. Decrypted content is never logged.
 */
import { randomUUID } from 'node:crypto'
import type { FastifyBaseLogger, FastifyInstance } from 'fastify'
import { decryptField, encryptField, outboxContentAad, unwrapAccountKey } from '@fma/crypto'
import { enqueueDraftSync, enqueueJob } from '@fma/db/job-queue'
import {
  OUTBOX_ERROR_MESSAGES,
  OUTBOX_LIMITS,
  isValidEmailAddress,
  isValidMessageId,
  type MailPerson,
  type OutboxContent,
  type OutboxErrorCode,
  type OutboxListResponse,
  type OutboxMessage,
  type OutboxStatus,
  type SendMessageJobPayload,
  type SendMessageRequest,
  type SentCopyStatus,
} from '@fma/shared'
import { requireAuth } from '../auth/routes'
import { IDENTITY_IS_DEFAULT } from './identities'

const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i
/** Generous body limit for long plain-text messages (UTF-8 up to 4 bytes/char). */
const BODY_LIMIT_BYTES = 4 * 1024 * 1024
const LIST_LIMIT = 100

interface OutboxRow {
  id: string
  account_id: string
  identity_id: string | null
  status: OutboxStatus
  content_enc: Buffer | null
  message_id_header: string
  attempts: number
  last_error_code: string | null
  sent_copy: SentCopyStatus | null
  created_at: Date
  sent_at: Date | null
  wrapped_dek: Buffer
}

const OUTBOX_COLUMNS = `o.id, o.account_id, o.identity_id, o.status, o.content_enc,
  o.message_id_header, o.attempts, o.last_error_code, o.sent_copy, o.created_at, o.sent_at,
  a.wrapped_dek`

type ParsedRequest = Omit<SendMessageRequest, 'to' | 'cc' | 'bcc'> & {
  to: MailPerson[]
  cc: MailPerson[]
  bcc: MailPerson[]
  references: string[]
  clientId?: string
  draftId?: string
}

/** Removes line breaks (header injection) and trims. */
function singleLine(value: string): string {
  return value.replace(/[\r\n]+/g, ' ').trim()
}

function parsePeople(value: unknown): MailPerson[] | null {
  if (value === undefined) return []
  if (!Array.isArray(value)) return null
  const people: MailPerson[] = []
  for (const entry of value) {
    const raw: { name?: unknown; address?: unknown } =
      typeof entry === 'string' ? { address: entry } : (entry ?? {})
    if (typeof raw.address !== 'string') return null
    if (raw.name !== undefined && typeof raw.name !== 'string') return null
    const address = raw.address.trim()
    if (!isValidEmailAddress(address)) return null
    const name = singleLine(typeof raw.name === 'string' ? raw.name : '')
    if (name.length > OUTBOX_LIMITS.maxNameLength) return null
    people.push({ name, address })
  }
  return people
}

/** Validates the request; returns a German error message on failure. */
export function parseSendRequest(body: unknown): ParsedRequest | string {
  if (!body || typeof body !== 'object') return 'Ungültige Anfrage.'
  const input = body as Record<string, unknown>
  if (typeof input.accountId !== 'string' || !UUID_RE.test(input.accountId)) {
    return 'Ungültiges Konto.'
  }
  if (
    input.identityId !== undefined &&
    (typeof input.identityId !== 'string' || !UUID_RE.test(input.identityId))
  ) {
    return 'Ungültige Absenderidentität.'
  }
  const to = parsePeople(input.to)
  const cc = parsePeople(input.cc)
  const bcc = parsePeople(input.bcc)
  if (!to || !cc || !bcc) return 'Ungültige Empfängeradresse.'
  const total = to.length + cc.length + bcc.length
  if (total === 0) return 'Mindestens ein Empfänger ist erforderlich.'
  if (total > OUTBOX_LIMITS.maxRecipients) {
    return `Höchstens ${OUTBOX_LIMITS.maxRecipients} Empfänger sind erlaubt.`
  }
  if (typeof input.subject !== 'string') return 'Ungültiger Betreff.'
  const subject = singleLine(input.subject)
  if (subject.length > OUTBOX_LIMITS.maxSubjectLength) return 'Der Betreff ist zu lang.'
  if (typeof input.text !== 'string') return 'Ungültiger Nachrichtentext.'
  if (input.text.length > OUTBOX_LIMITS.maxTextLength) return 'Der Nachrichtentext ist zu lang.'
  if (input.inReplyTo !== undefined && !isValidMessageId(input.inReplyTo)) {
    return 'Ungültiger In-Reply-To-Header.'
  }
  const references = input.references ?? []
  if (
    !Array.isArray(references) ||
    references.length > OUTBOX_LIMITS.maxReferences ||
    !references.every(isValidMessageId)
  ) {
    return 'Ungültiger References-Header.'
  }
  if (
    input.clientId !== undefined &&
    (typeof input.clientId !== 'string' || !UUID_RE.test(input.clientId))
  ) {
    return 'Ungültige Client-ID.'
  }
  if (
    input.draftId !== undefined &&
    (typeof input.draftId !== 'string' || !UUID_RE.test(input.draftId))
  ) {
    return 'Ungültige Entwurfs-ID.'
  }
  return {
    accountId: input.accountId.toLowerCase(),
    identityId: input.identityId?.toLowerCase(),
    to,
    cc,
    bcc,
    subject,
    text: input.text,
    inReplyTo: input.inReplyTo,
    references,
    clientId: input.clientId?.toLowerCase(),
    draftId: input.draftId?.toLowerCase(),
  }
}

function errorOf(code: string | null): OutboxMessage['error'] {
  if (!code) return null
  const known = (code in OUTBOX_ERROR_MESSAGES ? code : 'UNKNOWN') as OutboxErrorCode
  return { code: known, message: OUTBOX_ERROR_MESSAGES[known] }
}

function toOutboxMessage(log: FastifyBaseLogger, row: OutboxRow): OutboxMessage {
  let content: OutboxContent | null = null
  if (row.content_enc) {
    try {
      const dek = unwrapAccountKey(process.env.MASTER_KEY ?? '', row.wrapped_dek)
      content = JSON.parse(
        decryptField(dek, row.content_enc.toString('utf8'), outboxContentAad(row.id)),
      ) as OutboxContent
    } catch {
      log.warn({ outboxId: row.id }, 'outbox content could not be decrypted')
    }
  }
  return {
    id: row.id,
    accountId: row.account_id,
    identityId: row.identity_id,
    status: row.status,
    subject: content?.subject ?? null,
    from: content?.from ?? null,
    to: content?.to ?? [],
    cc: content?.cc ?? [],
    bcc: content?.bcc ?? [],
    messageId: row.message_id_header,
    attempts: row.attempts,
    error: errorOf(row.last_error_code),
    sentCopy: row.sent_copy,
    createdAt: row.created_at.toISOString(),
    sentAt: row.sent_at?.toISOString() ?? null,
  }
}

export async function outboxRoutes(app: FastifyInstance): Promise<void> {
  const pool = app.authPool

  /** Entry queued earlier with the same client id (idempotent repeat), if any. */
  async function loadByClientId(accountId: string, clientId: string): Promise<OutboxRow | null> {
    const { rows } = await pool.query<OutboxRow>(
      `SELECT ${OUTBOX_COLUMNS}
       FROM outbox_message o JOIN mail_account a ON a.id = o.account_id
       WHERE o.account_id = $1 AND o.client_id = $2`,
      [accountId, clientId],
    )
    return rows[0] ?? null
  }

  async function loadOwned(id: string, userId: string): Promise<OutboxRow | null> {
    if (!UUID_RE.test(id)) return null
    const { rows } = await pool.query<OutboxRow>(
      `SELECT ${OUTBOX_COLUMNS}
       FROM outbox_message o JOIN mail_account a ON a.id = o.account_id
       WHERE o.id = $1 AND a.user_id = $2`,
      [id, userId],
    )
    return rows[0] ?? null
  }

  app.post<{ Body: unknown }>(
    '/api/outbox',
    { preHandler: requireAuth, bodyLimit: BODY_LIMIT_BYTES },
    async (request, reply) => {
      const parsed = parseSendRequest(request.body)
      if (typeof parsed === 'string') {
        await reply.code(400).send({ message: parsed })
        return
      }

      const { rows: accounts } = await pool.query<{
        id: string
        display_name: string
        email_address: string
        wrapped_dek: Buffer
      }>(
        `SELECT id, display_name, email_address, wrapped_dek
         FROM mail_account WHERE id = $1 AND user_id = $2`,
        [parsed.accountId, request.auth!.userId],
      )
      const account = accounts[0]
      if (!account) {
        await reply.code(404).send({ message: 'Konto nicht gefunden.' })
        return
      }
      if (parsed.clientId) {
        const existing = await loadByClientId(account.id, parsed.clientId)
        if (existing) {
          await reply.code(200).send(toOutboxMessage(request.log, existing))
          return
        }
      }

      // Explicit identity, or the default one (see IDENTITY_IS_DEFAULT).
      const { rows: identities } = await pool.query<{
        id: string
        name: string
        email_address: string
      }>(
        parsed.identityId
          ? `SELECT id, name, email_address FROM identity WHERE account_id = $1 AND id = $2`
          : `SELECT i.id, i.name, i.email_address
             FROM identity i JOIN mail_account a ON a.id = i.account_id
             WHERE i.account_id = $1
             ORDER BY ${IDENTITY_IS_DEFAULT} DESC, i.email_address LIMIT 1`,
        parsed.identityId ? [account.id, parsed.identityId] : [account.id],
      )
      const identity = identities[0]
      if (parsed.identityId && !identity) {
        await reply.code(404).send({ message: 'Absenderidentität nicht gefunden.' })
        return
      }
      const from: MailPerson = identity
        ? { name: singleLine(identity.name), address: identity.email_address }
        : { name: singleLine(account.display_name), address: account.email_address }

      const id = randomUUID()
      const domain = from.address.split('@').pop() || 'localhost'
      const messageId = `<${randomUUID()}@${domain}>`
      const content: OutboxContent = {
        from,
        to: parsed.to,
        cc: parsed.cc,
        bcc: parsed.bcc,
        subject: parsed.subject,
        text: parsed.text,
      }
      const dek = unwrapAccountKey(process.env.MASTER_KEY ?? '', account.wrapped_dek)
      const contentEnc = Buffer.from(
        encryptField(dek, JSON.stringify(content), outboxContentAad(id)),
        'utf8',
      )

      const client = await pool.connect()
      try {
        await client.query('BEGIN')
        await client.query(
          `INSERT INTO outbox_message
             (id, account_id, identity_id, status, content_enc, message_id_header,
              in_reply_to, "references", client_id)
           VALUES ($1, $2, $3, 'queued', $4, $5, $6, $7, $8)`,
          [
            id,
            account.id,
            identity?.id ?? null,
            contentEnc,
            messageId,
            parsed.inReplyTo ?? null,
            parsed.references,
            parsed.clientId ?? null,
          ],
        )
        const payload: SendMessageJobPayload = { outboxId: id }
        await enqueueJob(client, {
          type: 'send_message',
          accountId: account.id,
          payload: { ...payload },
        })
        if (parsed.draftId) {
          // The draft is done: delete it, the worker removes its IMAP copy.
          const { rowCount } = await client.query(
            `UPDATE draft SET deleted_at = now(), content_enc = NULL, updated_at = now()
             WHERE id = $1 AND account_id = $2 AND deleted_at IS NULL`,
            [parsed.draftId, account.id],
          )
          if (rowCount) await enqueueDraftSync(client, account.id, parsed.draftId)
        }
        await client.query('COMMIT')
      } catch (err) {
        await client.query('ROLLBACK').catch(() => {})
        // Concurrent repeat with the same client id: answer with the winner.
        const existing =
          parsed.clientId && (err as { code?: string }).code === '23505'
            ? await loadByClientId(account.id, parsed.clientId)
            : null
        if (!existing) throw err
        await reply.code(200).send(toOutboxMessage(request.log, existing))
        return
      } finally {
        client.release()
      }

      const row = await loadOwned(id, request.auth!.userId)
      await reply.code(201).send(toOutboxMessage(request.log, row!))
    },
  )

  app.get<{ Params: { id: string } }>(
    '/api/outbox/:id',
    { preHandler: requireAuth },
    async (request, reply) => {
      const row = await loadOwned(request.params.id, request.auth!.userId)
      if (!row) {
        await reply.code(404).send({ message: 'Nachricht nicht gefunden.' })
        return
      }
      await reply.send(toOutboxMessage(request.log, row))
    },
  )

  app.get<{ Params: { id: string } }>(
    '/api/accounts/:id/outbox',
    { preHandler: requireAuth },
    async (request, reply) => {
      const accountId = request.params.id
      const { rows: owned } = UUID_RE.test(accountId)
        ? await pool.query('SELECT 1 FROM mail_account WHERE id = $1 AND user_id = $2', [
            accountId,
            request.auth!.userId,
          ])
        : { rows: [] }
      if (owned.length === 0) {
        await reply.code(404).send({ message: 'Konto nicht gefunden.' })
        return
      }
      const { rows } = await pool.query<OutboxRow>(
        `SELECT ${OUTBOX_COLUMNS}
         FROM outbox_message o JOIN mail_account a ON a.id = o.account_id
         WHERE o.account_id = $1 AND o.status IN ('queued', 'sending', 'failed')
         ORDER BY o.created_at DESC, o.id
         LIMIT ${LIST_LIMIT}`,
        [accountId],
      )
      const body: OutboxListResponse = {
        messages: rows.map((row) => toOutboxMessage(request.log, row)),
      }
      await reply.send(body)
    },
  )

  app.post<{ Params: { id: string } }>(
    '/api/outbox/:id/retry',
    { preHandler: requireAuth },
    async (request, reply) => {
      const row = await loadOwned(request.params.id, request.auth!.userId)
      if (!row) {
        await reply.code(404).send({ message: 'Nachricht nicht gefunden.' })
        return
      }
      const client = await pool.connect()
      try {
        await client.query('BEGIN')
        // Only failed messages, and only once (concurrent retries race on the status).
        const { rowCount } = await client.query(
          `UPDATE outbox_message SET status = 'queued', last_error_code = NULL, updated_at = now()
           WHERE id = $1 AND status = 'failed'`,
          [row.id],
        )
        if (rowCount === 0) {
          await client.query('ROLLBACK')
          await reply
            .code(409)
            .send({ message: 'Nur fehlgeschlagene Nachrichten können erneut gesendet werden.' })
          return
        }
        const payload: SendMessageJobPayload = { outboxId: row.id }
        await enqueueJob(client, {
          type: 'send_message',
          accountId: row.account_id,
          payload: { ...payload },
        })
        await client.query('COMMIT')
      } catch (err) {
        await client.query('ROLLBACK').catch(() => {})
        throw err
      } finally {
        client.release()
      }
      const updated = await loadOwned(row.id, request.auth!.userId)
      await reply.send(toOutboxMessage(request.log, updated!))
    },
  )
}
