// Generated by packages/design-tokens/generate.mjs from tokens.json (#141). Do not edit; run `pnpm tokens`.
package net.fma.mail.ui.theme

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp

object FmaTokens {
    object Light {
        val base100 = Color(0xFFFFFFFF)
        val base200 = Color(0xFFF5F7FA)
        val base300 = Color(0xFFE3E8EE)
        val baseContent = Color(0xFF1F2933)
        val primary = Color(0xFF0F5CB5)
        val primaryContent = Color(0xFFFFFFFF)
        val secondary = Color(0xFF6D3FC0)
        val secondaryContent = Color(0xFFFFFFFF)
        val accent = Color(0xFF0F766E)
        val accentContent = Color(0xFFFFFFFF)
        val neutral = Color(0xFF2F3B47)
        val neutralContent = Color(0xFFF5F7FA)
        val info = Color(0xFF1D6FD6)
        val infoContent = Color(0xFFFFFFFF)
        val success = Color(0xFF127146)
        val successContent = Color(0xFFFFFFFF)
        val warning = Color(0xFFC27A06)
        val warningContent = Color(0xFF1F1400)
        val error = Color(0xFFB42318)
        val errorContent = Color(0xFFFFFFFF)
    }

    object Dark {
        val base100 = Color(0xFF161B22)
        val base200 = Color(0xFF1D242D)
        val base300 = Color(0xFF2A333E)
        val baseContent = Color(0xFFDFE5EC)
        val primary = Color(0xFF5EA2F2)
        val primaryContent = Color(0xFF06182C)
        val secondary = Color(0xFFB18CF0)
        val secondaryContent = Color(0xFF1A0C33)
        val accent = Color(0xFF3CC3B4)
        val accentContent = Color(0xFF04201D)
        val neutral = Color(0xFFCFD7E0)
        val neutralContent = Color(0xFF161B22)
        val info = Color(0xFF6AAAF5)
        val infoContent = Color(0xFF06182C)
        val success = Color(0xFF4CC38A)
        val successContent = Color(0xFF04200F)
        val warning = Color(0xFFE6A73A)
        val warningContent = Color(0xFF231600)
        val error = Color(0xFFF2726A)
        val errorContent = Color(0xFF2B0503)
    }

    object Radius {
        val selector = 6.dp
        val field = 6.dp
        val box = 8.dp
    }
}
