// Design tokens (#141): tokens.json is the single source. This script
// writes the Compose theme constants for apps/mobile and checks that the
// PWA's daisyUI themes (apps/web/app/assets/css/main.css) use the same
// values. No dependencies.
// Usage: node packages/design-tokens/generate.mjs [--check]
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

const root = fileURLToPath(new URL('../../', import.meta.url))
export const TOKENS_PATH = `${root}packages/design-tokens/tokens.json`
export const KOTLIN_PATH = `${root}apps/mobile/composeApp/src/commonMain/kotlin/net/fma/mail/ui/theme/FmaTokens.kt`
export const CSS_PATH = `${root}apps/web/app/assets/css/main.css`

const camel = (name) =>
  name.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase()).replace(/^(\d)/, '_$1')
const kotlinColor = (hex) => {
  if (!/^#[0-9a-fA-F]{6}$/.test(hex)) throw new Error(`unsupported color ${hex}`)
  return `Color(0xFF${hex.slice(1).toUpperCase()})`
}
const remToDp = (rem) => {
  const match = /^([\d.]+)rem$/.exec(rem)
  if (!match) throw new Error(`unsupported length ${rem}`)
  return `${Number(match[1]) * 16}.dp`
}

export function renderKotlin(tokens) {
  const palette = (name, colors) =>
    [
      `    object ${name} {`,
      ...Object.entries(colors).map(([k, v]) => `        val ${camel(k)} = ${kotlinColor(v)}`),
      '    }',
    ].join('\n')
  return `// Generated by packages/design-tokens/generate.mjs from tokens.json (#141). Do not edit; run \`pnpm tokens\`.
package net.fma.mail.ui.theme

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp

object FmaTokens {
${palette('Light', tokens.color.light)}

${palette('Dark', tokens.color.dark)}

    object Radius {
${Object.entries(tokens.radius)
  .map(([k, v]) => `        val ${camel(k)} = ${remToDp(v)}`)
  .join('\n')}
    }
}
`
}

/** Values in main.css that differ from the tokens, as readable lines. */
export function cssMismatches(tokens, css) {
  const themes = {}
  for (const block of css.split("@plugin 'daisyui/theme'").slice(1)) {
    const name = /name:\s*'([^']+)'/.exec(block)?.[1]
    if (name) themes[name] = block.slice(0, block.indexOf('}'))
  }
  const problems = []
  for (const [mode, theme] of [
    ['light', 'fma-light'],
    ['dark', 'fma-dark'],
  ]) {
    const block = themes[theme]
    if (!block) {
      problems.push(`theme ${theme} missing in main.css`)
      continue
    }
    const check = (variable, expected) => {
      const actual = new RegExp(`${variable}:\\s*([^;]+);`).exec(block)?.[1]?.trim()
      if (actual?.toLowerCase() !== expected.toLowerCase())
        problems.push(`${theme} ${variable}: css ${actual}, tokens ${expected}`)
    }
    for (const [key, value] of Object.entries(tokens.color[mode])) check(`--color-${key}`, value)
    for (const [key, value] of Object.entries(tokens.radius)) check(`--radius-${key}`, value)
  }
  return problems
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const tokens = JSON.parse(readFileSync(TOKENS_PATH, 'utf8'))
  const kotlin = renderKotlin(tokens)
  const problems = cssMismatches(tokens, readFileSync(CSS_PATH, 'utf8'))
  if (process.argv.includes('--check')) {
    let current = ''
    try {
      current = readFileSync(KOTLIN_PATH, 'utf8')
    } catch {
      // missing file is reported below
    }
    if (current !== kotlin) problems.push(`${KOTLIN_PATH} is out of date: run pnpm tokens`)
  } else {
    writeFileSync(KOTLIN_PATH, kotlin)
  }
  if (problems.length > 0) {
    console.error(problems.join('\n'))
    process.exit(1)
  }
}
