<?php

declare(strict_types=1);

namespace Fma\Install;

use Fma\Auth\SetupCode;
use Fma\Config;
use Fma\Db\Database;
use Fma\Db\Migrator;
use Fma\Http\Middleware\CsrfProtection;
use Fma\Log\Logger;
use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\ServerRequestInterface;
use Slim\Psr7\Response;

/**
 * Web installer for webspace without shell access (#109), served by
 * public/install.php. It shows the SystemCheck results, suggests a
 * config.php (with a fresh MASTER_KEY and VAPID keys, never written to
 * disk), applies migrations and hands out a first-run setup code.
 *
 * - Disabled (404) as soon as a user exists.
 * - Never prints configured secrets (MASTER_KEY, database password,
 *   SETUP_TOKEN); only whether they are set.
 * - POST actions need a same-origin request (CsrfProtection).
 * - A setup code is only shown after the MASTER_KEY has been entered: it
 *   proves control over config.php, so a stranger who finds a fresh
 *   instance cannot claim it. The entered key is compared, never echoed.
 */
final class Installer
{
    public function __construct(
        private readonly Config $config,
        private readonly Database $db,
        private readonly string $migrationsDir,
        private readonly string $configFile,
        private readonly ?SystemCheck $check = null,
    ) {}

    public function handle(ServerRequestInterface $request): ResponseInterface
    {
        if ($this->userExists()) {
            return self::page(404, 'Not found', '<p>Not found.</p>');
        }
        $method = $request->getMethod();
        if ($method !== 'GET' && $method !== 'HEAD' && $method !== 'POST') {
            return self::page(405, 'Method not allowed', '<p>Method not allowed.</p>')->withHeader('Allow', 'GET, POST');
        }
        if (CsrfProtection::isCrossOrigin($request)) {
            return self::page(403, 'Forbidden', '<p>Cross-origin request rejected.</p>');
        }
        $notice = '';
        if ($method === 'POST') {
            $body = $request->getParsedBody();
            $body = \is_array($body) ? $body : [];
            $action = \is_string($body['action'] ?? null) ? $body['action'] : '';
            $notice = match ($action) {
                'migrate' => $this->migrate(),
                'setup-code' => $this->setupCode($body['master_key'] ?? null),
                default => self::notice(false, 'Unknown action.'),
            };
        }
        $network = ($request->getQueryParams()['network'] ?? '') === '1';

        return self::page(200, 'Installation', $notice . $this->overview($request, $network));
    }

    /**
     * Fresh VAPID key pair (P-256) in the base64url format of scripts/setup-env.mjs.
     *
     * @return array{public: string, private: string}|null
     */
    public static function generateVapidKeys(): ?array
    {
        $key = openssl_pkey_new(['private_key_type' => OPENSSL_KEYTYPE_EC, 'curve_name' => 'prime256v1']);
        if ($key === false) {
            return null;
        }
        $details = openssl_pkey_get_details($key);
        if ($details === false || !isset($details['ec']['x'], $details['ec']['y'], $details['ec']['d'])) {
            return null;
        }
        $ec = $details['ec'];
        $pad = static fn(string $bytes): string => str_pad($bytes, 32, "\0", STR_PAD_LEFT);

        return [
            'public' => self::base64url("\x04" . $pad($ec['x']) . $pad($ec['y'])),
            'private' => self::base64url($pad($ec['d'])),
        ];
    }

    /**
     * config.php suggestion; only contains freshly generated values and placeholders.
     *
     * @param array{public: string, private: string}|null $vapid
     */
    public static function configTemplate(string $masterKey, ?array $vapid): string
    {
        $lines = [
            '<?php',
            '',
            'declare(strict_types=1);',
            '',
            '// Generated by install.php. Save as config.php OUTSIDE the web root',
            '// (next to vendor/), permissions 0600. Back up MASTER_KEY separately.',
            'return [',
            "    'MASTER_KEY' => '{$masterKey}',",
            "    'MASTER_KEY_ID' => 'v1',",
            "    'DATABASE_URL' => 'mysql://USER:PASSWORD@localhost:3306/DATABASE',",
        ];
        if ($vapid !== null) {
            $lines[] = "    'VAPID_PUBLIC_KEY' => '{$vapid['public']}',";
            $lines[] = "    'VAPID_PRIVATE_KEY' => '{$vapid['private']}',";
            $lines[] = "    'VAPID_SUBJECT' => 'mailto:admin@example.com',";
        }
        $lines[] = "    'LOG_LEVEL' => 'info',";
        $lines[] = '];';

        return implode("\n", $lines) . "\n";
    }

    private function userExists(): bool
    {
        try {
            return Database::run($this->db->pdo(), 'SELECT EXISTS (SELECT 1 FROM `user`)')->fetchColumn() == 1;
        } catch (\Throwable) {
            // No database or no schema yet: installation is not finished.
            return false;
        }
    }

    private function migrate(): string
    {
        try {
            $applied = (new Migrator($this->db->pdo(), $this->migrationsDir))->migrate();

            return self::notice(true, \count($applied) . ' migration(s) applied.');
        } catch (\Throwable $e) {
            // No message: driver errors may contain connection details.
            return self::notice(false, 'Migration failed (' . $e::class . '). Check the database settings.');
        }
    }

    private function setupCode(mixed $masterKey): string
    {
        if (trim($this->config->get('SETUP_TOKEN')) !== '') {
            return self::notice(false, 'SETUP_TOKEN is configured: use that value as setup code.');
        }
        $expected = $this->config->get('MASTER_KEY');
        if ($expected === '' || !\is_string($masterKey) || !hash_equals(hash('sha256', $expected), hash('sha256', trim($masterKey)))) {
            return self::notice(false, 'MASTER_KEY does not match the configured one.');
        }
        try {
            $code = (new SetupCode($this->config, $this->db, new Logger('install')))->regenerate();
        } catch (\Throwable $e) {
            return self::notice(false, 'Could not create a setup code (' . $e::class . '). Apply the migrations first.');
        }

        return self::notice(true, 'Setup code (replaces earlier ones, valid until setup is done): <code class="big">' . self::e($code) . '</code>'
            . '<br>Open the app, choose the first-run setup and enter this code.');
    }

    private function overview(ServerRequestInterface $request, bool $network): string
    {
        $checks = ($this->check ?? new SystemCheck($this->config))->run($network);
        $checks[] = $this->configLocationCheck($request);
        $rows = '';
        foreach ($checks as $check) {
            $state = $check['ok'] ? 'ok' : ($check['required'] ? 'fail' : 'warn');
            $rows .= '<tr class="' . $state . '"><td>' . strtoupper($state) . '</td><td>' . self::e($check['name']) . '</td><td>' . self::e($check['detail']) . '</td></tr>';
        }
        $html = '<h2>1. System check</h2>'
            . '<p>' . (SystemCheck::passed($checks) ? 'All required checks passed.' : 'Some required checks failed.') . ' '
            . ($network ? '<a href="?">Without network probes</a>' : '<a href="?network=1">Also probe outbound IMAP/SMTP ports</a> (takes a few seconds)') . '</p>'
            . '<table><thead><tr><th>State</th><th>Check</th><th>Detail</th></tr></thead><tbody>' . $rows . '</tbody></table>';

        $html .= '<h2>2. Configuration</h2>';
        if ($this->config->get('MASTER_KEY') === '') {
            $html .= '<p>No MASTER_KEY configured. Save this suggestion as <code>' . self::e(basename($this->configFile)) . '</code> outside the web root '
                . '(expected at <code>' . self::e($this->configFile) . '</code>), fill in the database URL and reload. '
                . 'The values are generated for this page only and are not stored anywhere. '
                . '<strong>Back up the MASTER_KEY separately</strong> – without it all mails and credentials are unreadable.</p>'
                . '<pre>' . self::e(self::configTemplate(SystemCheck::generateMasterKey(), self::generateVapidKeys())) . '</pre>';
        } else {
            $html .= '<p>MASTER_KEY is configured (not shown). Keep a backup of it separate from the server.</p>';
        }

        $html .= '<h2>3. Database schema</h2><form method="post"><input type="hidden" name="action" value="migrate">'
            . '<button type="submit">Apply migrations</button></form>';

        $html .= '<h2>4. First-run setup code</h2>';
        if (trim($this->config->get('SETUP_TOKEN')) !== '') {
            $html .= '<p>SETUP_TOKEN is configured: use that value as setup code.</p>';
        } else {
            $html .= '<p>Enter the configured MASTER_KEY to prove you control this installation. A new setup code is generated and shown once '
                . '(like <code>php bin/setup-code.php</code>).</p>'
                . '<form method="post"><input type="hidden" name="action" value="setup-code">'
                . '<input type="password" name="master_key" autocomplete="off" required placeholder="MASTER_KEY" aria-label="MASTER_KEY"> '
                . '<button type="submit">Show setup code</button></form>';
        }

        return $html . '<p class="hint">This installer switches itself off (404) once the first user has been created. '
            . 'Background jobs: set up a cron job for <code>bin/cron.php</code> or the web cron (<code>cron.php</code> with CRON_TOKEN).</p>';
    }

    /**
     * config.php must not be reachable over HTTP: it must not live below the document root.
     *
     * @return array{name: string, ok: bool, required: bool, detail: string}
     */
    private function configLocationCheck(ServerRequestInterface $request): array
    {
        $docRoot = $request->getServerParams()['DOCUMENT_ROOT'] ?? '';
        $root = \is_string($docRoot) && $docRoot !== '' ? realpath($docRoot) : false;
        $dir = realpath(\dirname($this->configFile));
        if ($root === false || $dir === false) {
            return ['name' => 'config.php outside the web root', 'ok' => true, 'required' => false, 'detail' => 'could not determine, check manually'];
        }
        $inside = $dir === $root || str_starts_with($dir . '/', rtrim($root, '/') . '/');

        return ['name' => 'config.php outside the web root', 'ok' => !$inside, 'required' => true, 'detail' => $inside ? 'move config.php (and vendor/, src/) above the web root' : ''];
    }

    private static function notice(bool $ok, string $html): string
    {
        return '<div class="notice ' . ($ok ? 'ok' : 'fail') . '" role="status">' . $html . '</div>';
    }

    private static function page(int $status, string $title, string $body): ResponseInterface
    {
        $html = '<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">'
            . '<meta name="robots" content="noindex"><title>' . self::e($title) . ' – Mail</title><style>'
            . 'body{font:15px/1.5 system-ui,sans-serif;max-width:52rem;margin:0 auto;padding:1rem;color:#1d1d1f;background:#fff}'
            . 'table{border-collapse:collapse;width:100%}td,th{text-align:left;padding:.3rem .5rem;border-bottom:1px solid #ddd}'
            . 'tr.ok td:first-child{color:#17803d}tr.fail td:first-child{color:#c62828;font-weight:600}tr.warn td:first-child{color:#a15c00}'
            . 'pre{background:#f4f4f5;padding:.75rem;overflow-x:auto}.notice{padding:.75rem;margin:1rem 0;border-radius:6px}'
            . '.notice.ok{background:#e7f6ec}.notice.fail{background:#fdecea}.big{font-size:1.3em}.hint{color:#555}'
            . '@media (prefers-color-scheme:dark){body{background:#151517;color:#eee}pre{background:#26262a}td,th{border-color:#333}'
            . '.notice.ok{background:#173d24}.notice.fail{background:#4a1c1c}.hint{color:#aaa}}'
            . '</style></head><body><h1>' . self::e($title) . '</h1>' . $body . '</body></html>';
        $response = new Response($status);
        $response->getBody()->write($html);

        return $response
            ->withHeader('Content-Type', 'text/html; charset=utf-8')
            ->withHeader('Cache-Control', 'no-store')
            ->withHeader('Content-Security-Policy', "default-src 'none'; style-src 'unsafe-inline'; form-action 'self'; frame-ancestors 'none'; base-uri 'none'")
            ->withHeader('X-Content-Type-Options', 'nosniff')
            ->withHeader('Referrer-Policy', 'no-referrer')
            ->withHeader('X-Robots-Tag', 'noindex');
    }

    private static function e(string $value): string
    {
        return htmlspecialchars($value, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
    }

    private static function base64url(string $bytes): string
    {
        return rtrim(strtr(base64_encode($bytes), '+/', '-_'), '=');
    }
}
