#!/usr/bin/env bash
# Builds the shared-hosting ZIP of the PHP backend (#109, ADR-0013):
#
#   fma-<version>/
#     public_html/          -> upload into the web root (document root)
#       index.html, _nuxt/, sw.js, ...   static PWA build (apps/web)
#       .htaccess            SPA fallback, /api/* -> api/index.php, security headers
#       api/index.php        thin wrapper -> fma-app/public/index.php
#       install.php          web installer (404 once a user exists)
#       cron.php             web cron (404 without CRON_TOKEN)
#       app-path.php         where fma-app lives (default: ../fma-app)
#     fma-app/              -> upload NEXT TO the web root, never into it
#       src/ bin/ migrations/ vendor/ public/ config.example.php
#       config.php           created by the operator (installer suggests it)
#       data/                encrypted mails (MAIL_DATA_DIR default)
#
# Layout: docs/operations/installation-php.md.
#
# Needs the web build: pnpm --filter @fma/web build
# Usage: scripts/build-php-release.sh [--version X.Y.Z] [--out DIR] [--local-vendor]
#   --local-vendor  reuse apps/server-php/vendor instead of downloading
#                   packages (offline smoke test); dev packages are removed.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PHP_APP="$ROOT/apps/server-php"
WEB_OUT="$ROOT/apps/web/.output"
VERSION="$(node -p "require('$ROOT/package.json').version" 2>/dev/null || echo 0.0.0-dev)"
OUT="$ROOT/dist"
LOCAL_VENDOR=0

while [ $# -gt 0 ]; do
  case "$1" in
    --version) VERSION="$2"; shift 2 ;;
    --out) OUT="$2"; shift 2 ;;
    --local-vendor) LOCAL_VENDOR=1; shift ;;
    *) echo "unknown option: $1" >&2; exit 2 ;;
  esac
done

if [ ! -f "$WEB_OUT/public/index.html" ] || [ ! -f "$WEB_OUT/security-headers.conf" ]; then
  echo "ERROR: web build missing - run: pnpm --filter @fma/web build" >&2
  exit 1
fi
command -v composer >/dev/null || { echo "ERROR: composer not found" >&2; exit 1; }
command -v zip >/dev/null || { echo "ERROR: zip not found" >&2; exit 1; }

NAME="fma-$VERSION"
STAGE="$(mktemp -d)"
trap 'rm -rf "$STAGE"' EXIT
PKG="$STAGE/$NAME"
WEBROOT="$PKG/public_html"
APP="$PKG/fma-app"
mkdir -p "$WEBROOT/api" "$APP/data"

# --- application (outside the web root) ---
cp -R "$PHP_APP/src" "$PHP_APP/bin" "$PHP_APP/migrations" "$PHP_APP/public" "$APP/"
cp "$PHP_APP/composer.json" "$PHP_APP/composer.lock" "$PHP_APP/config.example.php" "$PHP_APP/.htaccess" "$APP/"
cp "$PHP_APP/.htaccess" "$APP/data/.htaccess"
cp "$ROOT/LICENSE" "$PKG/LICENSE"
if [ "$LOCAL_VENDOR" = 1 ]; then
  cp -R "$PHP_APP/vendor" "$APP/vendor"
  # Removes the dev packages already present; nothing to download.
  (cd "$APP" && COMPOSER_DISABLE_NETWORK=1 composer install --no-dev --no-interaction --no-progress --no-scripts --optimize-autoloader --quiet)
else
  (cd "$APP" && composer install --no-dev --no-interaction --no-progress --no-scripts --prefer-dist --optimize-autoloader --quiet)
fi
# Source installs (--prefer-source fallback) bring VCS metadata along.
find "$APP/vendor" -name .git -type d -prune -exec rm -rf {} +
rm -f "$APP/composer.lock"
printf '%s\n' "$VERSION" > "$APP/VERSION"

# --- web root ---
cp -R "$WEB_OUT/public/." "$WEBROOT/"

cat > "$WEBROOT/app-path.php" <<'PHP'
<?php

declare(strict_types=1);

// Directory of the application (src/, vendor/, config.php). Default layout:
// fma-app/ next to the web root. Adjust if your hoster needs another place,
// but never move fma-app into the web root.
return __DIR__ . '/../fma-app';
PHP

for entry in api/index.php:index.php install.php:install.php cron.php:cron.php; do
  target="${entry%%:*}"
  script="${entry##*:}"
  prefix="__DIR__ . '/app-path.php'"
  [ "$target" = "api/index.php" ] && prefix="__DIR__ . '/../app-path.php'"
  cat > "$WEBROOT/$target" <<PHP
<?php

declare(strict_types=1);

// Generated by scripts/build-php-release.sh: runs fma-app/public/$script.
require (require $prefix) . '/public/$script';
PHP
done

# Security headers of the PWA: same values as the nginx snippet written by
# apps/web/scripts/build-csp.mjs (CSP with inline-script hashes).
HEADERS="$(sed -n 's/^add_header \([A-Za-z-]*\) \(".*"\) always;$/    Header always set \1 \2/p' "$WEB_OUT/security-headers.conf")"
[ -n "$HEADERS" ] || { echo "ERROR: no headers parsed from security-headers.conf" >&2; exit 1; }

cat > "$WEBROOT/.htaccess" <<HTACCESS
# Generated by scripts/build-php-release.sh ($VERSION). Apache 2.4 with
# mod_rewrite and mod_headers (AllowOverride All). Install at the root of a
# (sub)domain: the service worker and the routes expect /.
Options -Indexes
DirectoryIndex index.html
AddType application/manifest+json .webmanifest

<IfModule mod_rewrite.c>
  RewriteEngine On
  # PHP-FPM/CGI drops the Authorization header (web cron, /api/metrics).
  RewriteCond %{HTTP:Authorization} .
  RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
  # API: everything below /api/ goes to the front controller.
  RewriteCond %{REQUEST_URI} !^/api/index\.php$
  RewriteRule ^api/ api/index.php [QSA,L]
  # SPA fallback for client-side routes.
  RewriteCond %{REQUEST_FILENAME} !-f
  RewriteCond %{REQUEST_FILENAME} !-d
  RewriteRule ^ index.html [L]
</IfModule>

# Never serve hidden files or the path helper.
<FilesMatch "^(\.|app-path\.php$)">
  Require all denied
</FilesMatch>

<IfModule mod_headers.c>
  Header always unset X-Powered-By
  Header always set Strict-Transport-Security "max-age=31536000" "expr=%{HTTPS} == 'on'"
  # PWA headers (apps/web/nginx.conf); api, installer and web cron set their own.
  <If "%{REQUEST_URI} !~ m#^/(api/|install\.php|cron\.php)#">
$HEADERS
  </If>
  # Hashed assets are immutable, HTML, service worker and manifest revalidate.
  <If "%{REQUEST_URI} =~ m#^/_nuxt/#">
    Header set Cache-Control "public, max-age=31536000, immutable"
  </If>
  <ElseIf "%{REQUEST_URI} =~ m#^/icons/#">
    Header set Cache-Control "public, max-age=86400"
  </ElseIf>
  <ElseIf "%{REQUEST_URI} =~ m#^/(index\.html|sw\.js|manifest\.webmanifest)?\$#">
    Header set Cache-Control "no-cache"
  </ElseIf>
</IfModule>
HTACCESS

cat > "$PKG/INSTALL.txt" <<TXT
Mail $VERSION - shared hosting package (preview)

public_html/  -> contents into the web root of a (sub)domain
fma-app/      -> next to the web root (NOT inside it)

Then open https://<your-domain>/install.php and follow the steps.
Full guide: docs/operations/installation-php.md in the repository.
TXT

mkdir -p "$OUT"
ZIP="$OUT/$NAME-php.zip"
rm -f "$ZIP"
(cd "$STAGE" && zip -qr -X "$ZIP" "$NAME")
echo "Written: $ZIP"
