#!/bin/sh
# First-time setup for the docker compose deployment (ADR-0007, ADR-0013):
# generates a .env with a random MASTER_KEY, a VAPID key pair and
# MARIADB_PASSWORD. Never overwrites an existing .env. Needs only openssl.
#
# The MASTER_KEY never leaves this machine: it is only written to .env and
# must be backed up separately from the database (see .env.example).
set -eu

cd "$(dirname "$0")/.."
ENV_FILE="$PWD/.env"

if [ -e "$ENV_FILE" ]; then
  echo "ERROR: $ENV_FILE already exists - not overwriting." >&2
  exit 1
fi

b64url() {
  base64 | tr '+/' '-_' | tr -d '=\n'
}

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

MASTER_KEY="$(openssl rand -base64 32)"
MARIADB_PASSWORD="$(openssl rand 24 | b64url)"

# VAPID: P-256 key pair as raw public point (65 bytes) and raw private
# scalar (32 bytes), base64url - the format of the VAPID spec. The DER
# layouts are fixed for P-256: the point is the last 65 bytes of the
# SubjectPublicKeyInfo, the scalar starts at byte 7 of the SEC1 key.
openssl ecparam -name prime256v1 -genkey -noout -out "$TMP/vapid.pem"
VAPID_PUBLIC_KEY="$(openssl ec -in "$TMP/vapid.pem" -pubout -outform DER 2>/dev/null | tail -c 65 | b64url)"
VAPID_PRIVATE_KEY="$(openssl ec -in "$TMP/vapid.pem" -no_public -outform DER 2>/dev/null |
  dd bs=1 skip=7 count=32 2>/dev/null | b64url)"

umask 077
cat >"$ENV_FILE" <<EOF
# Generated by scripts/setup-env.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)

# ":80" = local HTTP without TLS. Set your domain here for Let's Encrypt TLS.
DOMAIN=:80

# WARNING: if the MASTER_KEY is lost, all encrypted data is unrecoverable.
# Back it up separately from database backups!
MASTER_KEY=$MASTER_KEY

VAPID_PUBLIC_KEY=$VAPID_PUBLIC_KEY
VAPID_PRIVATE_KEY=$VAPID_PRIVATE_KEY
VAPID_SUBJECT=mailto:admin@example.com

MARIADB_PASSWORD=$MARIADB_PASSWORD
EOF

echo "Written: $ENV_FILE"
echo "IMPORTANT: back up the MASTER_KEY somewhere safe and separate."
