#!/usr/bin/env node
/**
 * First-time setup for the docker compose deployment (ADR-0007):
 * generates a .env with a random MASTER_KEY, VAPID key pair and
 * POSTGRES_PASSWORD. Never overwrites an existing .env.
 *
 * The MASTER_KEY never leaves this machine: it is only written to .env
 * and must be backed up separately from the database (see .env.example).
 */
import { generateKeyPairSync, randomBytes } from 'node:crypto'
import { existsSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

const envPath = fileURLToPath(new URL('../.env', import.meta.url))

if (existsSync(envPath)) {
  console.error(`ERROR: ${envPath} already exists - not overwriting.`)
  process.exit(1)
}

const masterKey = randomBytes(32).toString('base64')

// VAPID keys: P-256 key pair, encoded as raw public point / scalar in base64url
// (the format web-push and the VAPID spec use).
const { publicKey, privateKey } = generateKeyPairSync('ec', { namedCurve: 'prime256v1' })
const pubJwk = publicKey.export({ format: 'jwk' })
const vapidPublicKey = Buffer.concat([
  Buffer.from([0x04]),
  Buffer.from(pubJwk.x, 'base64url'),
  Buffer.from(pubJwk.y, 'base64url'),
]).toString('base64url')
const vapidPrivateKey = privateKey.export({ format: 'jwk' }).d

const postgresPassword = randomBytes(24).toString('base64url')
const mariadbPassword = randomBytes(24).toString('base64url')

const content = `# Generated by scripts/setup-env.mjs on ${new Date().toISOString()}

# ":80" = local HTTP without TLS. Set your domain here for Let's Encrypt TLS.
DOMAIN=:80

# WARNING: if the MASTER_KEY is lost, all encrypted data is unrecoverable.
# Back it up separately from database backups!
MASTER_KEY=${masterKey}

VAPID_PUBLIC_KEY=${vapidPublicKey}
VAPID_PRIVATE_KEY=${vapidPrivateKey}
VAPID_SUBJECT=mailto:admin@example.com

POSTGRES_USER=mail
POSTGRES_PASSWORD=${postgresPassword}
POSTGRES_DB=mail

# Only for the PHP backend preview (docker-compose.php.yml).
MARIADB_PASSWORD=${mariadbPassword}
`

writeFileSync(envPath, content, { mode: 0o600 })
console.log(`Written: ${envPath}`)
console.log('IMPORTANT: back up the MASTER_KEY somewhere safe and separate.')
